# Generated by Django 4.2.4 on 2024-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_choices',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='availability',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
