# Generated by Django 4.2.4 on 2024-02-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_unit_inventory_inventory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='unit_choices',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
