# Generated by Django 4.2.4 on 2024-02-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredients_unit_choices_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cashier_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
